### ISSUE TITLE
Twilio mms attachments not working because latest phpList requires uid query parameter

### ISSUE THREAD

**Issue by jrblakely** [bramley/phplist-plugin-twilio#1]
Apparently in the latest phpList release, the dl.php file requires a query parameter of uid set to the users uniqid value.

The dl.php page is returning a 404 error when uid is not included.

**Comment by bramley** [comment]
Yes, that was changed in 2019. I'll need to look into this because at the point in the processing where the download link is created we don't have the details of the user who the email is being sent to.

As a very quick workaround you can add a fixed uid, because it only has to be a valid uid. Change line 174

                $mediaUrls[] = sprintf('%s://%s%s/dl.php?id=%d', $public_scheme, $website, $pageroot, $row['id']);

to e.g. if uid 1 exists

                $mediaUrls[] = sprintf('%s://%s%s/dl.php?id=%d&uid=1', $public_scheme, $website, $pageroot, $row['id']);

**Comment by bramley** [comment]
I confused uid with id, a uid is a 32 character value.

**Comment by jrblakely** [comment]
Hi Duncan,

The **uid** is actually the **uniqid** from the **user** table, and it appears to be _a_ uuid value, but not _the_ uuid value.

I feel validated that I did use an existing admin user's **uniqid** for the **uid** string as that user is likely to be around at least until the code is updated.

I'm not sure if it is feasible to use a placeholder token for the attachment **uid**, and then to replace it with the user **uniqid** just before sending to Twilio, but that's a thought.

One final edge case I noticed in testing. the lookup of attachments doesn't necessarily correspond to the actual file uploaded by the user. The query returns all attachment records with the same **name** and selects the unique **remotefile** name of the first record found (the one with the lowest **id**, I believe). 

I'm not sure if the **cid** from the **mailer** attachments corresponds to the attachments table or not, but that would be a better query value to use if it does. Absent that, taking the  most recent (highest id) attachment (e.g `order by id, desc limit 1`) would probably be better than taking the oldest one.

**Comment by bramley** [comment]
> The uid is actually the uniqid from the user table, and it appears to be a uuid value, but not the uuid value.

Yes, that is what I had intended to convey.

I see your point about selecting the attachment. At this point of the processing the only useful information that we have is the file name, which is not necessarily unique in the attachments table
![image](https://user-images.githubusercontent.com/3147688/194232155-5bb99f7b-25f7-4ced-8543-bc20e596c098.png)


Using the most recently uploaded seems to be more correct, so I will change that.

An alternative simpler approach is to use the message_attachment table, which identifies exactly which attachment file to use for that message. I think that I used the attachments actually on the email that has been constructed in case, for some reason, those are not the same as the phplist table. But that might not be a valid concern.

**Comment by bramley** [comment]
I have made the change to include the uid parameter and to use the message_attachment table to identify the attachments. There are also a few more changes to bring the code in line with the current phplist and common plugin, which simplifies some areas.

You can upgrade the plugin on the Manage Plugins page. You will need to update Common Plugin to 3.22.1 as well as upgrading this plugin. You might want to backup any code changes that you have made, just in case. But I have tested this so far as I can using the Twilio test credentials.

**Comment by jrblakely** [comment]
I tested the issues I was having with sending an attachment due to missing uid and sending via API, and both tests passed.

I was not able to confirm the edge case of duplicate filenames with different content, but that is not a typical use case and it is easily addressed by forcing a unique filename if it were important. It might actually be a nice enhancement to _intentionally reuse_ an existing file, but you'd have to think through the implications of that.
